name: salami_cli
description: A Salami Command Line Interface for Dart
version: 0.0.1-dev.0
homepage: https://github.com/HeyDevTalents

environment:
  sdk: ">=2.8.1 <3.0.0"

dev_dependencies:
  very_good_analysis: ^2.4.0

executables:
  salami:
