name: salami_cli

on:
  pull_request:
    paths:
      - ".github/workflows/salami_cli.yaml"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/salami_cli.yaml"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: subosito/flutter-action@v1.5.3

      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: flutter format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze lib test

      - name: Verify Build
        run: flutter pub run test --run-skipped -t pull-request-only

      - name: Run Tests
        run: |
          flutter pub global activate coverage
          flutter pub run test -j 1 -x pull-request-only -x e2e --coverage=coverage --test-randomize-ordering-seed random && dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib

      - name: Coverde Check
        run: coverde check 100

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0

  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: subosito/flutter-action@v1.5.3

      - name: Install Dependencies
        run: |
          flutter pub get
          dart pub global activate coverde
          dart pub global activate melos

      - name: Run Tests
        run: flutter pub run test --run-skipped -t e2e
